

<div id='conteudo'>

	<?php foreach($this->view->usuarios as $usuario) { ?>
					<div class="row mb-2">
						<div class="col">
							<div class="card">
								<div class="card-body">
									<div class="row">
										<div class="col-md-6">
											<?= $usuario['nome'] ?>
										</div>
									
										<div class="col-md-6 d-flex justify-content-end">
											<div>
												<?php if ($usuario['seguindo_sn'] === 0) { ?>
													<a href="/acao?acao=seguir&id_usuario=<?=$usuario['id']?>&user_procurado=<?=$this->view->nome_procurado?>" class="btn btn-success">Seguir</a>
												<?php } else if ($usuario['seguindo_sn'] === 1) { ?>
													<a href="/acao?acao=deixar_de_seguir&id_usuario=<?=$usuario['id']?>&user_procurado=<?=$this->view->nome_procurado?>" class="btn btn-danger">Deixar de seguir</a>
												<?php } ?>
											</div>
										</div>	
									</div>	
								</div>	
							</div>
						</div>
					</div>					
				<?php } ?>
</div>

